import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Banner from '../layout/Banner'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className=" max-w-[1440px] mx-auto border-3 border-green-500">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <Navbar/>
        <Banner/>
      </main>
    </div>
  )
}

export default Home
